version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: companydb
    ports:
      - "3308:3306"  
    volumes:
      - test-mysql-data:/var/lib/mysql
  api:
    build:
      context: .
    container_name: test-api
    env_file:
      - .env.test
    depends_on:
      - db
    command: >
      sh -c "until mysqladmin ping -h db -u root -proot --silent; do echo waiting for db; sleep 3; done && npm test"

volumes:
  test-mysql-data:
