services:
  test-mysql:
    image: mysql:8
    container_name: test-mysql
    # No need to expose any ports for test
    # Just use internal Docker networking
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: companydb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - testnet

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - test-mysql
    networks:
      - testnet
    entrypoint: ["sh", "-c", "sleep 10 && npm run test:ci"]

networks:
  testnet:
