services:
  test-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - testnet

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - test-mysql
    networks:
      - testnet
    entrypoint: ["sh", "-c", "sleep 10 && npm run test:ci"]

networks:
  testnet:
