version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: test-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: companydb
    volumes:
      - ./db/database.sql:/docker-entrypoint-initdb.d/1_database.sql
      - ./db/procedures.sql:/docker-entrypoint-initdb.d/2_procedures.sql
    ports:
      - "3307:3306" # or whatever you’re using

  api:
    build:
      context: .
    container_name: test-api
    env_file:
      - .env.test
    depends_on:
      - db
    command: ["sh", "./wait-for.sh"]

volumes:
  test-mysql-data:
