version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: test-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: companydb
    ports:
      - "3307:3306"
    volumes:
      - test-mysql-data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-api
    environment:
      - NODE_ENV=test
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=companydb
      - DB_PORT=3306
    depends_on:
      - db
    command: >
      sh -c "npx dotenv -e .env.test -- npm test"

volumes:
  test-mysql-data:
