services:
  test-mysql:
    image: mysql:5.7
    container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: companydb
    ports:
      - "3308:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
    container_name: test-api
    depends_on:
      - test-mysql
    env_file:
      - .env.test
    command: ["sh", "./wait-for.sh"]
