version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: test-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: companydb
    volumes:
     - ./db:/docker-entrypoint-initdb.d


  api:
    build:
      context: .
    container_name: test-api
    env_file:
      - .env.test
    depends_on:
      - db
    command: ["sh", "./wait-for.sh"]

volumes:
  test-mysql-data:
