version: '3.8'

services:
  test-mysql:
    image: mysql:8
    container_name: test-mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: companydb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - testnet

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - test-mysql
    networks:
      - testnet
    entrypoint: ["sh", "-c", "sleep 10 && npm run test:ci"]

networks:
  testnet:

sonarqube:
  image: sonarqube:lts
  ports:
    - "9000:9000"
  environment:
    - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
  networks:
    - testnet
