version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: companydb
    ports:
      - "3308:3306"
    volumes:
      - ./db/database.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/procedures.sql:/docker-entrypoint-initdb.d/2.sql

  node-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: node-api
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: companydb
      DB_PORT: 3306