version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: companydb
    ports:
      - "3308:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - test-mysql-data:/var/lib/mysql
  api:
    build:
      context: .
    container_name: test-api
    env_file:
      - .env.test
    depends_on:
      - localhost
    command: ["sh", "./wait-for.sh"]

volumes:
  test-mysql-data:
