version: '3.8'

services:
  test-mysql:
    image: mysql:8
    container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: companydb
    ports:
      - "3306:3306"
    networks:
      - testnet

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - test-mysql
    env_file:
      - .env.test
    command: ["./wait-for.sh", "test-mysql:3306", "--", "npm", "test"]
    networks:
      - testnet

networks:
  testnet:
