version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: companydb
    ports:
      - "3308:3306"
    volumes:
      - ./db/database.sql:/docker-entrypoint-initdb.d/1-database.sql
      - ./db/procedures.sql:/docker-entrypoint-initdb.d/2-procedures.sql

  api:
    build:
      context: .
    container_name: test-api
    env_file:
      - .env.test
    depends_on:
      - db
    command: ["sh", "./wait-for.sh"]

volumes:
  test-mysql-data:
